// Generates the on-disk "skill" alternative to the live MCP transport:
// a SKILL.md (frontmatter + usage docs) plus a small dependency-free Node
// CLI script that POSTs to XLM Studio's control API (see mcpServer.ts's
// handleControlApi). Written to the default skills location:
//   Windows: C:\Users\<User>\.agents\skills\xlm-studio\
//   macOS/Linux: ~/.agents/skills/xlm-studio/
import { existsSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { homedir } from 'os'
import { join } from 'path'
import type { McpSettings } from '../shared/types'
import { TOOL_DEFS } from './mcpControl'

const SKILL_NAME = 'xlm-studio'

export function skillDir(): string {
  return join(homedir(), '.agents', 'skills', SKILL_NAME)
}

function buildSkillMd(mcp: McpSettings): string {
  const enabledTools = TOOL_DEFS.filter(t => mcp.tools[t.name as keyof typeof mcp.tools] !== false)
  const toolDocs = enabledTools.map(t => {
    const paramsLine = t.params.length === 0
      ? '  No arguments.'
      : t.params.map(p => `  - ${p.name} (${p.type}${p.required ? ', required' : ', optional'}): ${p.description}`).join('\n')
    return `### ${t.name}\n${t.description}\n${paramsLine}\n\nExample:\n\`\`\`\nnode ${SKILL_NAME}-control.cjs ${t.name} '${JSON.stringify(Object.fromEntries(t.params.filter(p => p.required).map(p => [p.name, p.type.includes('[]') ? [] : p.type === 'number' ? 0 : '...'])))}'\n\`\`\``
  }).join('\n\n')

  return `---
name: ${SKILL_NAME}
description: Control the locally-running XLM Studio app — inspect models/backends/RAM/VRAM, switch, start/stop, create/duplicate/edit, apply parameter presets, and benchmark model Templates. Use this whenever the user asks to manage, inspect, switch, start, stop, or benchmark their local llama.cpp-style Templates in XLM Studio.
---

# XLM Studio control skill

XLM Studio must be running on this machine with Settings -> MCP Server turned on for this skill to work. All commands below run through a single CLI script that talks to XLM Studio's local control API on \`http://127.0.0.1:${mcp.port}\`.

Run commands from this skill's folder:

\`\`\`
node ${SKILL_NAME}-control.cjs <tool-name> '<json-args>'
\`\`\`

The script prints the tool's JSON result to stdout, or \`{"error": "..."}\` with a non-zero exit code on failure.

${mcp.restrictEditToMcpMade ? 'NOTE: "Only allow Template edits via MCP for MCP-made Templates" is ON — template-edit will refuse to touch a Template that was not itself created via template-create/template-duplicate (i.e. one that does not carry the "MCP-made" tag).' : ''}

IMPORTANT — switch-template is lifecycle-only: it starts/stops Templates and reports ports, it does NOT hand a live chat conversation between models. If you want to talk to several local models in turn as part of one session, hold the conversation yourself (in this session) and call template-action / switch-template to swap which backend is actually running underneath, one call per swap. If YOU are one of the models running inside a Template and you want to hand off to a different one, call switch-template yourself (stop yourself, start the other) — do not stop, then start in separate tool calls.

There is no reliable way for a Template to detect which port/Template it is itself running on. If info-templates shows more than one Template currently active, and you might be one of the models running inside one of them, ask the user which Template you are before calling switch-template. With only one Template active, this ambiguity doesn't arise, so no need to ask.

IMPORTANT — Benchmarks are more representative run one at a time, sequentially, rather than several in parallel — that better reflects a model's actual peak throughput unless you specifically intend to measure a multi-model-at-once setup.

## Available tools

${toolDocs}
`
}

function buildControlScript(mcp: McpSettings): string {
  // Deliberately dependency-free (plain Node 'http') so it runs with
  // whatever Node the agent's shell has available, no npm install needed.
  return `#!/usr/bin/env node
// Auto-generated by XLM Studio — do not edit by hand, it's rewritten on
// every "Add SKILL" and on every relevant settings change.
'use strict';
const http = require('http');

const TOOL = process.argv[2];
const ARGS_RAW = process.argv[3] || '{}';
const PORT = ${mcp.port};
const TOKEN = ${JSON.stringify(mcp.token)};

if (!TOOL) {
  console.error('Usage: node ${SKILL_NAME}-control.cjs <tool-name> \\'<json-args>\\'');
  process.exit(1);
}

let args;
try { args = JSON.parse(ARGS_RAW); } catch (e) {
  console.error('Second argument must be valid JSON: ' + e.message);
  process.exit(1);
}

const body = JSON.stringify(args);
const req = http.request({
  hostname: '127.0.0.1', port: PORT, path: '/control/' + TOOL, method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(body),
    'Authorization': 'Bearer ' + TOKEN
  }
}, res => {
  let data = '';
  res.on('data', chunk => { data += chunk; });
  res.on('end', () => {
    process.stdout.write(data + '\\n');
    process.exit(res.statusCode && res.statusCode >= 400 ? 1 : 0);
  });
});
req.on('error', err => {
  console.error(JSON.stringify({ error: 'Could not reach XLM Studio on 127.0.0.1:' + PORT + ' — is it running with MCP Server enabled? (' + err.message + ')' }));
  process.exit(1);
});
req.write(body);
req.end();
`
}

export function writeSkillFiles(mcp: McpSettings) {
  const dir = skillDir()
  try {
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, 'SKILL.md'), buildSkillMd(mcp))
    writeFileSync(join(dir, `${SKILL_NAME}-control.cjs`), buildControlScript(mcp), { mode: 0o755 })
  } catch (err) {
    console.error('[skillGenerator] Failed to write skill files:', err)
  }
}

export function removeSkillFiles() {
  const dir = skillDir()
  try {
    if (existsSync(dir)) rmSync(dir, { recursive: true, force: true })
  } catch (err) {
    console.error('[skillGenerator] Failed to remove skill files:', err)
  }
}
